"""
MWEB HTML Reporter
==================
Generate HTML format reports with styling.
"""

from typing import Dict, Any
from pathlib import Path
from .base import BaseReporter


class HTMLReporter(BaseReporter):
    """Generate HTML reports."""
    
    def generate(self, target: str, results: Dict[str, Any]) -> str:
        """Generate HTML report."""
        filename = self.output_dir / f"mweb_report_{target}_{self._get_timestamp()}.html"
        
        risk = self._calculate_risk_score(results)
        
        content = self._build_html(target, results, risk)
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return str(filename)
    
    def _build_html(self, target: str, results: Dict[str, Any], risk: Dict[str, Any]) -> str:
        """Build HTML content."""
        
        css = """
        <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
                   line-height: 1.6; color: #333; background: #f5f5f5; padding: 20px; }
            .container { max-width: 1200px; margin: 0 auto; background: white; 
                        border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); padding: 30px; }
            h1 { color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 10px; }
            h2 { color: #444; margin-top: 30px; border-bottom: 1px solid #ddd; padding-bottom: 8px; }
            .summary { background: #f8fafc; padding: 20px; border-radius: 6px; margin: 20px 0; }
            .score { font-size: 48px; font-weight: bold; text-align: center; }
            .score.good { color: #16a34a; }
            .score.fair { color: #f59e0b; }
            .score.poor { color: #ea580c; }
            .score.critical { color: #dc2626; }
            table { width: 100%; border-collapse: collapse; margin: 15px 0; }
            th, td { padding: 12px; text-align: left; border-bottom: 1px solid #e5e7eb; }
            th { background: #f9fafb; font-weight: 600; }
            code { background: #f3f4f6; padding: 2px 6px; border-radius: 3px; font-family: monospace; }
            .alert { padding: 15px; border-radius: 6px; margin: 15px 0; }
            .alert-danger { background: #fee2e2; border-left: 4px solid #dc2626; }
        </style>
        """
        
        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>MWEB Report - {target}</title>
    {css}
</head>
<body>
    <div class="container">
        <h1>🔒 MWEB Reconnaissance Report</h1>
        
        <div class="summary">
            <h3>Target: <code>{target}</code></h3>
            <div class="score {risk['rating'].lower()}">{risk['score']}/100</div>
            <p style="text-align: center;">Rating: {risk['rating']}</p>
        </div>
        
        <h2>Findings</h2>
        {self._render_findings(risk['findings'])}
        
        <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; 
                      color: #666; text-align: center;">
            Generated by MWEB
        </footer>
    </div>
</body>
</html>"""
        
        return html
    
    def _render_findings(self, findings: list) -> str:
        if not findings:
            return '<div class="alert" style="background: #dcfce7;">✅ No critical issues</div>'
        
        html = '<div class="alert alert-danger">'
        for finding in findings:
            html += f'<p>⚠️ {finding}</p>'
        html += '</div>'
        return html
