"""
MWEB Markdown Reporter
======================
Generate Markdown format reports.
"""

from typing import Dict, Any
from pathlib import Path
from .base import BaseReporter


class MarkdownReporter(BaseReporter):
    """Generate Markdown reports."""
    
    def generate(self, target: str, results: Dict[str, Any]) -> str:
        """Generate Markdown report."""
        filename = self.output_dir / f"mweb_report_{target}_{self._get_timestamp()}.md"
        
        risk = self._calculate_risk_score(results)
        
        content = self._build_report(target, results, risk)
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return str(filename)
    
    def _build_report(self, target: str, results: Dict[str, Any], risk: Dict[str, Any]) -> str:
        """Build report content."""
        lines = [
            f"# MWEB Reconnaissance Report",
            f"",
            f"**Target:** `{target}`",
            f"**Generated:** {self._get_timestamp()}",
            f"**Risk Score:** {risk['score']}/100 ({risk['rating']})",
            f"",
            f"---",
            f"",
            f"## Executive Summary",
            f"",
            f"Security posture rated as **{risk['rating']}**.",
            f"",
            f"### Key Findings",
            f""
        ]
        
        if risk['findings']:
            for finding in risk['findings']:
                lines.append(f"- ⚠️ {finding}")
        else:
            lines.append("- No critical issues identified")
        
        lines.extend(["", "---", ""])
        
        # Add module sections
        if "whois" in results:
            lines.extend(self._format_whois(results["whois"]))
        if "dns" in results:
            lines.extend(self._format_dns(results["dns"]))
        if "ipgeo" in results:
            lines.extend(self._format_ipgeo(results["ipgeo"]))
        if "http" in results:
            lines.extend(self._format_http(results["http"]))
        if "ssl_tls" in results:
            lines.extend(self._format_ssl(results["ssl_tls"]))
        if "crawler" in results:
            lines.extend(self._format_crawler(results["crawler"]))
        
        lines.append("")
        lines.append("*Generated by MWEB*")
        
        return "\n".join(lines)
    
    def _format_whois(self, result: Dict) -> list:
        lines = ["## WHOIS Information", ""]
        if not result.get("success"):
            lines.append(f"❌ Error: {result.get('errors', ['Unknown'])[0]}")
            return lines
        
        data = result.get("data", {})
        lines.extend([
            f"| Field | Value |",
            f"|-------|-------|",
            f"| Registrar | {data.get('registrar', 'N/A')} |",
            f"| Creation Date | {data.get('creation_date', 'N/A')} |",
            f"| Expiration Date | {data.get('expiration_date', 'N/A')} |",
            f""
        ])
        return lines
    
    def _format_dns(self, result: Dict) -> list:
        lines = ["## DNS Records", ""]
        data = result.get("data", {})
        records = data.get("records", {})
        
        for rtype, values in records.items():
            lines.append(f"### {rtype} Records")
            for val in values:
                lines.append(f"- `{val}`")
            lines.append("")
        return lines
    
    def _format_ipgeo(self, result: Dict) -> list:
        lines = ["## IP Geolocation", ""]
        data = result.get("data", {})
        lines.append(f"**Resolved IPs:** {', '.join(data.get('resolved_ips', []))}")
        lines.append("")
        return lines
    
    def _format_http(self, result: Dict) -> list:
        lines = ["## HTTP Analysis", ""]
        data = result.get("data", {})
        
        for url, headers in data.get("security_headers", {}).items():
            lines.append(f"**{url}**")
            if headers.get("missing"):
                lines.append("Missing headers: " + ", ".join(headers["missing"]))
            lines.append("")
        return lines
    
    def _format_ssl(self, result: Dict) -> list:
        lines = ["## SSL/TLS Certificate", ""]
        data = result.get("data", {})
        cert = data.get("certificate", {})
        
        lines.append(f"**Subject:** {cert.get('subject', {})}")
        lines.append(f"**Issuer:** {cert.get('issuer', {})}")
        lines.append(f"**Valid Until:** {cert.get('not_after', 'N/A')}")
        
        if data.get("vulnerabilities"):
            lines.append("")
            lines.append("### Vulnerabilities")
            for vuln in data["vulnerabilities"]:
                lines.append(f"- 🔴 {vuln}")
        lines.append("")
        return lines
    
    def _format_crawler(self, result: Dict) -> list:
        lines = ["## Discovery Files", ""]
        data = result.get("data", {})
        
        if data.get("robots_txt"):
            lines.append("### robots.txt")
            lines.append("```")
            lines.append(data["robots_txt"][:500])
            lines.append("```")
        return lines
